apiVersion: v1
kind: Service
metadata:
  name: my-api-route-service
spec:
  selector:
    app: api-route
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 8080
  type: LoadBalancer
